In [1]:
import numpy as np   
import pandas as pd                           

In [2]:
df=pd.read_csv(r"C:\smartbridge_datasets\diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            8      183             64              0        0  23.3   
2            0      137             40             35      168  43.1   
3            3       78             50             32       88  31.0   
4            2      197             70             45      543  30.5   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos  
1                     0.672   32      pos  
2                     2.288   33      pos  
3                     0.248   26      pos  
4                     0.158   53      pos

In [4]:
df.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [5]:
df.Diabetes.unique()

array(['pos', 'neg'], dtype=object)

In [6]:
x=df.iloc[:,0:8].values
y=df.iloc[:,8:9].values

In [7]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
y

array([['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       [

In [9]:
y.shape

(549, 1)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [11]:
y.shape

(549, 2)

In [12]:
y

array([[0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       ...,
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=0)

In [14]:
x_train=np.asarray(x_train).astype('float32')
x_test=np.asarray(x_test).astype('float32')
y_train=np.asarray(y_train).astype('float32')
y_test=np.asarray(y_test).astype('float32')

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential   
from tensorflow.keras.layers import Dense

In [18]:
a=Sequential()

In [19]:
a.add(Dense(8,kernel_initializer= "random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [20]:
a.add(Dense(16,kernel_initializer= "random_uniform",activation="relu"))

In [21]:
a.add(Dense(2,kernel_initializer= "random_uniform",activation="sigmoid"))

In [22]:
a.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [23]:
a.fit(x_train,y_train,batch_size=32,epochs=1000)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/1000
439/439 [==============================] - 2s 4ms/sample - loss: 0.6931 - acc: 0.5011
Epoch 2/1000
439/439 [==============================] - 0s 70us/sample - loss: 0.6928 - acc: 0.5011
Epoch 3/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.6918 - acc: 0.5410
Epoch 4/1000
439/439 [==============================] - 0s 80us/sample - loss: 0.6891 - acc: 0.6834
Epoch 5/1000
439/439 [==============================] - 0s 77us/sample - loss: 0.6833 - acc: 0.7118
Epoch 6/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.6729 - acc: 0.7369
Epoch 7/1000
439/439 [==============================] - 0s 66us/sample - loss: 0.6565 - acc: 0.7563
Epoch 8/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.6362 - acc: 0.7597
Epoch 9/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.6165 - acc: 0.7699
Epoch 1

Epoch 79/1000
439/439 [==============================] - 0s 70us/sample - loss: 0.4288 - acc: 0.8178
Epoch 80/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.4285 - acc: 0.8132
Epoch 81/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.4279 - acc: 0.8109
Epoch 82/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.4272 - acc: 0.8132
Epoch 83/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.4271 - acc: 0.8178
Epoch 84/1000
439/439 [==============================] - ETA: 0s - loss: 0.3504 - acc: 0.875 - 0s 59us/sample - loss: 0.4264 - acc: 0.8132
Epoch 85/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.4258 - acc: 0.8098
Epoch 86/1000
439/439 [==============================] - 0s 64us/sample - loss: 0.4257 - acc: 0.8132
Epoch 87/1000
439/439 [==============================] - 0s 79us/sample - loss: 0.4253 - acc: 0.8132
Epoch 88/1000
439/439 [==============================

439/439 [==============================] - 0s 120us/sample - loss: 0.4036 - acc: 0.8223
Epoch 160/1000
439/439 [==============================] - 0s 91us/sample - loss: 0.4035 - acc: 0.8223
Epoch 161/1000
439/439 [==============================] - 0s 84us/sample - loss: 0.4034 - acc: 0.8292
Epoch 162/1000
439/439 [==============================] - 0s 84us/sample - loss: 0.4029 - acc: 0.8212
Epoch 163/1000
439/439 [==============================] - 0s 66us/sample - loss: 0.4022 - acc: 0.8235
Epoch 164/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.4020 - acc: 0.8246
Epoch 165/1000
439/439 [==============================] - 0s 80us/sample - loss: 0.4019 - acc: 0.8246
Epoch 166/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.4015 - acc: 0.8235
Epoch 167/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.4017 - acc: 0.8200
Epoch 168/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.4012 - acc: 0

439/439 [==============================] - 0s 70us/sample - loss: 0.3805 - acc: 0.8292
Epoch 320/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.3806 - acc: 0.8269
Epoch 321/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3812 - acc: 0.8292
Epoch 322/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3806 - acc: 0.8326
Epoch 323/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.3801 - acc: 0.8314
Epoch 324/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3800 - acc: 0.8337
Epoch 325/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3796 - acc: 0.8360
Epoch 326/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3795 - acc: 0.8314
Epoch 327/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3804 - acc: 0.8360
Epoch 328/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3801 - acc: 0.

439/439 [==============================] - 0s 82us/sample - loss: 0.3665 - acc: 0.8383
Epoch 480/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3666 - acc: 0.8349
Epoch 481/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3663 - acc: 0.8383
Epoch 482/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3666 - acc: 0.8360
Epoch 483/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3655 - acc: 0.8360
Epoch 484/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3662 - acc: 0.8383
Epoch 485/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3667 - acc: 0.8405
Epoch 486/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3659 - acc: 0.8360
Epoch 487/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3667 - acc: 0.8383
Epoch 488/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3645 - acc: 0.

439/439 [==============================] - 0s 77us/sample - loss: 0.3504 - acc: 0.8519
Epoch 640/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3501 - acc: 0.8542
Epoch 641/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3501 - acc: 0.8542
Epoch 642/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3496 - acc: 0.8542
Epoch 643/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3501 - acc: 0.8565
Epoch 644/1000
439/439 [==============================] - 0s 66us/sample - loss: 0.3499 - acc: 0.8588
Epoch 645/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3495 - acc: 0.8565
Epoch 646/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3501 - acc: 0.8519
Epoch 647/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3492 - acc: 0.8542
Epoch 648/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3495 - acc: 0.

439/439 [==============================] - 0s 73us/sample - loss: 0.3430 - acc: 0.8588
Epoch 800/1000
439/439 [==============================] - 0s 80us/sample - loss: 0.3433 - acc: 0.8565
Epoch 801/1000
439/439 [==============================] - 0s 82us/sample - loss: 0.3424 - acc: 0.8542
Epoch 802/1000
439/439 [==============================] - 0s 70us/sample - loss: 0.3420 - acc: 0.8519
Epoch 803/1000
439/439 [==============================] - 0s 77us/sample - loss: 0.3433 - acc: 0.8565
Epoch 804/1000
439/439 [==============================] - 0s 84us/sample - loss: 0.3417 - acc: 0.8565
Epoch 805/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3442 - acc: 0.8554
Epoch 806/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3425 - acc: 0.8519
Epoch 807/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3427 - acc: 0.8542
Epoch 808/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3428 - acc: 0.

439/439 [==============================] - 0s 55us/sample - loss: 0.3371 - acc: 0.8508
Epoch 960/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.3357 - acc: 0.8588
Epoch 961/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3361 - acc: 0.8565
Epoch 962/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3377 - acc: 0.8565
Epoch 963/1000
439/439 [==============================] - 0s 64us/sample - loss: 0.3360 - acc: 0.8565
Epoch 964/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3357 - acc: 0.8565
Epoch 965/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3358 - acc: 0.8565
Epoch 966/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3355 - acc: 0.8565
Epoch 967/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3362 - acc: 0.8565
Epoch 968/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3357 - acc: 0.

In [24]:
ypred=a.predict(x_test)
ypred

array([[3.28590870e-02, 9.66985583e-01],
       [3.04123759e-03, 9.96938348e-01],
       [2.96223640e-01, 7.03565598e-01],
       [3.52054834e-04, 9.99646425e-01],
       [9.59415793e-01, 4.06325161e-02],
       [2.92251706e-02, 9.70528603e-01],
       [9.58393693e-01, 4.15957272e-02],
       [2.00691164e-01, 7.99358130e-01],
       [1.58463478e-01, 8.41783643e-01],
       [1.04308128e-06, 9.99998927e-01],
       [9.62362885e-01, 3.77938747e-02],
       [1.59463882e-02, 9.84239638e-01],
       [7.37264454e-02, 9.26218688e-01],
       [2.72370666e-01, 7.27032363e-01],
       [7.96604514e-01, 2.03163058e-01],
       [8.02528858e-02, 9.19909000e-01],
       [9.31558490e-01, 6.85653687e-02],
       [9.02349591e-01, 9.75665450e-02],
       [4.75256205e-01, 5.23607790e-01],
       [3.83053809e-01, 6.16416812e-01],
       [8.92887712e-01, 1.06985092e-01],
       [6.33685589e-01, 3.66056800e-01],
       [2.20343947e-01, 7.81591177e-01],
       [1.22725964e-04, 9.99876738e-01],
       [9.864104

In [25]:
y_test

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [26]:
ypred[0]

array([0.03285909, 0.9669856 ], dtype=float32)

In [27]:
y_test[0]

array([0., 1.], dtype=float32)

In [28]:
a.predict(sc.transform([[8,183,64,0,0,23.3,0.672,32]]))

array([[0., 1.]], dtype=float32)

In [29]:
a.predict_classes(sc.transform([[8,183,64,0,0,23.3,0.672,32]]))

array([1], dtype=int64)