In [1]:
import numpy as np   
import pandas as pd       

In [2]:
df=pd.read_csv(r"C:\smartbridge_datasets\bank.csv")

In [3]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
df.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
df=df.drop(["marital","education","default"],axis=1)

In [6]:
df.head()

age         job  balance housing loan  contact  day month  duration  \
0   59      admin.     2343     yes   no  unknown    5   may      1042   
1   56      admin.       45      no   no  unknown    5   may      1467   
2   41  technician     1270     yes   no  unknown    5   may      1389   
3   55    services     2476     yes   no  unknown    5   may       579   
4   54      admin.      184      no   no  unknown    5   may       673   

   campaign  pdays  previous poutcome deposit  
0         1     -1         0  unknown     yes  
1         1     -1         0  unknown     yes  
2         1     -1         0  unknown     yes  
3         1     -1         0  unknown     yes  
4         2     -1         0  unknown     yes

In [7]:
df.job.unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [8]:
df.housing.unique()

array(['yes', 'no'], dtype=object)

In [9]:
df.loan.unique()

array(['no', 'yes'], dtype=object)

In [10]:
df.contact.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [11]:
df.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [12]:
df.poutcome.unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()      
df["job"]= le.fit_transform(df["job"])
df["housing"]= le.fit_transform(df["housing"])
df["loan"]= le.fit_transform(df["loan"])
df["contact"]= le.fit_transform(df["contact"])
df["month"]= le.fit_transform(df["month"])
df["poutcome"]= le.fit_transform(df["poutcome"])
df["deposit"]= le.fit_transform(df["deposit"])

In [14]:
x=df.iloc[:,:13].values
y=df.iloc[:,13:14].values

In [15]:
x

array([[  59,    0, 2343, ...,   -1,    0,    3],
       [  56,    0,   45, ...,   -1,    0,    3],
       [  41,    9, 1270, ...,   -1,    0,    3],
       ...,
       [  32,    9,   29, ...,   -1,    0,    3],
       [  43,    9,    0, ...,  172,    5,    0],
       [  34,    9,    0, ...,   -1,    0,    3]], dtype=int64)

In [16]:
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [17]:
x.shape

(11162, 13)

In [18]:
y.shape

(11162, 1)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=20)

In [20]:
x_train=np.asarray(x_train).astype('float32')
x_test=np.asarray(x_test).astype('float32')
y_train=np.asarray(y_train).astype('float32')
y_test=np.asarray(y_test).astype('float32')

In [21]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [22]:
from tensorflow.keras.models import Sequential   
from tensorflow.keras.layers import Dense

In [23]:
c=Sequential()

In [24]:
c.add(Dense(13,kernel_initializer= "random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [25]:
c.add(Dense(26,kernel_initializer= "random_uniform",activation="relu"))

In [26]:
c.add(Dense(1,kernel_initializer= "random_uniform",activation="sigmoid"))

In [27]:
c.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [28]:
c.fit(x_train,y_train,batch_size=32,epochs=100)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8929/8929 [==============================] - 1s 111us/sample - loss: 0.5531 - acc: 0.7352
Epoch 2/100
8929/8929 [==============================] - 0s 53us/sample - loss: 0.4531 - acc: 0.7970
Epoch 3/100
8929/8929 [==============================] - 0s 53us/sample - loss: 0.4460 - acc: 0.8004
Epoch 4/100
8929/8929 [==============================] - 0s 56us/sample - loss: 0.4403 - acc: 0.8048
Epoch 5/100
8929/8929 [==============================] - 0s 55us/sample - loss: 0.4362 - acc: 0.8045
Epoch 6/100
8929/8929 [==============================] - 1s 57us/sample - loss: 0.4341 - acc: 0.8061
Epoch 7/100
8929/8929 [==============================] - 1s 63us/sample - loss: 0.4317 - acc: 0.8061
Epoch 8/100
8929/8929 [==============================] - 1s 61us/sample - loss: 0.4309 - acc: 0.8071
Epoch 9/100
8929/8929 [==============================] - 0s 53us/sample - loss: 0.4273 - acc: 0.8

8929/8929 [==============================] - 0s 51us/sample - loss: 0.3958 - acc: 0.8222
Epoch 78/100
8929/8929 [==============================] - 0s 51us/sample - loss: 0.3948 - acc: 0.8224
Epoch 79/100
8929/8929 [==============================] - 0s 49us/sample - loss: 0.3951 - acc: 0.8225
Epoch 80/100
8929/8929 [==============================] - 0s 56us/sample - loss: 0.3937 - acc: 0.8262
Epoch 81/100
8929/8929 [==============================] - 0s 53us/sample - loss: 0.3947 - acc: 0.8237
Epoch 82/100
8929/8929 [==============================] - 0s 53us/sample - loss: 0.3943 - acc: 0.8242
Epoch 83/100
8929/8929 [==============================] - 0s 50us/sample - loss: 0.3940 - acc: 0.8230
Epoch 84/100
8929/8929 [==============================] - 0s 54us/sample - loss: 0.3940 - acc: 0.8245
Epoch 85/100
8929/8929 [==============================] - 1s 57us/sample - loss: 0.3924 - acc: 0.8250
Epoch 86/100
8929/8929 [==============================] - 1s 63us/sample - loss: 0.3925 - acc: 

In [30]:
ypred=c.predict(x_test)
ypred

array([[0.77898896],
       [0.9080199 ],
       [0.6335058 ],
       ...,
       [0.9427918 ],
       [0.00822687],
       [0.08234449]], dtype=float32)

In [31]:
y_test

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [0.],
       [0.]], dtype=float32)

In [32]:
ypred[0]

array([0.77898896], dtype=float32)

In [33]:
y_test[0]

array([1.], dtype=float32)

In [37]:
c.predict(sc.transform([[59,0,2343,1,0,2,5,8,1042,1,-1,0,3]]))

array([[0.8310026]], dtype=float32)

In [40]:
c.predict_classes(sc.transform([[39,7,733,0,0,2,16,6,83,4,-1,0,3]]))

array([[0]])