In [1]:
import numpy as np   
import pandas as pd   

In [2]:
df=pd.read_csv(r"C:\smartbridge_datasets\50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     49 non-null float64
Marketing Spend    49 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [6]:
df.Administration=df.Administration.fillna(df.Administration.mean())

In [7]:
df["Marketing Spend"]=df["Administration"].fillna(df["Marketing Spend"].mean())

In [8]:
df.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [9]:
df.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [10]:
x=df.iloc[:,[0,1,2,4]].values
y=df.iloc[:,3:4].values

In [11]:
x.shape

(50, 4)

In [12]:
y.shape

(50, 1)

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [14]:
y.shape

(50, 3)

In [15]:
y

array([[0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=100)

In [17]:
x_train=np.asarray(x_train).astype('float32')
x_test=np.asarray(x_test).astype('float32')
y_train=np.asarray(y_train).astype('float32')
y_test=np.asarray(y_test).astype('float32')

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential   
from tensorflow.keras.layers import Dense

In [20]:
b=Sequential()

In [21]:
b.add(Dense(4,kernel_initializer= "random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [22]:
b.add(Dense(8,kernel_initializer= "random_uniform",activation="relu"))

In [23]:
b.add(Dense(3,kernel_initializer= "random_uniform",activation="softmax"))

In [24]:
b.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [25]:
b.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
40/40 [==============================] - 1s 14ms/sample - loss: 1.0986 - acc: 0.3250
Epoch 2/1000
40/40 [==============================] - 0s 499us/sample - loss: 1.0984 - acc: 0.3750
Epoch 3/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0984 - acc: 0.3750
Epoch 4/1000
40/40 [==============================] - 0s 224us/sample - loss: 1.0982 - acc: 0.3750
Epoch 5/1000
40/40 [==============================] - 0s 175us/sample - loss: 1.0980 - acc: 0.3750
Epoch 6/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0980 - acc: 0.3750
Epoch 7/1000
40/40 [==============================] - 0s 224us/sample - loss: 1.0980 - acc: 0.3750
Epoch 8/1000
40/40 [==============================] - 0s 199us/sample - loss: 1.0979 - acc: 0.3750
Epoch 9/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0978 - acc: 0.3750
Epoch 10/1000
40/40 [==============================] - 0s 374us/sample - loss: 1.0978 - acc: 0.3750
Epoch 11/1

40/40 [==============================] - 0s 224us/sample - loss: 1.0535 - acc: 0.3750
Epoch 164/1000
40/40 [==============================] - 0s 274us/sample - loss: 1.0531 - acc: 0.3750
Epoch 165/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0528 - acc: 0.3750
Epoch 166/1000
40/40 [==============================] - 0s 175us/sample - loss: 1.0525 - acc: 0.3750
Epoch 167/1000
40/40 [==============================] - 0s 175us/sample - loss: 1.0520 - acc: 0.3750
Epoch 168/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0516 - acc: 0.3750
Epoch 169/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0513 - acc: 0.3750
Epoch 170/1000
40/40 [==============================] - 0s 150us/sample - loss: 1.0509 - acc: 0.3750
Epoch 171/1000
40/40 [==============================] - 0s 125us/sample - loss: 1.0506 - acc: 0.3750
Epoch 172/1000
40/40 [==============================] - 0s 125us/sample - loss: 1.0504 - acc: 0.3750
Epoch

40/40 [==============================] - 0s 175us/sample - loss: 1.0147 - acc: 0.4750
Epoch 325/1000
40/40 [==============================] - 0s 174us/sample - loss: 1.0145 - acc: 0.4750
Epoch 326/1000
40/40 [==============================] - 0s 175us/sample - loss: 1.0146 - acc: 0.4750
Epoch 327/1000
40/40 [==============================] - 0s 224us/sample - loss: 1.0144 - acc: 0.4750
Epoch 328/1000
40/40 [==============================] - 0s 125us/sample - loss: 1.0142 - acc: 0.4750
Epoch 329/1000
40/40 [==============================] - 0s 149us/sample - loss: 1.0140 - acc: 0.5000
Epoch 330/1000
40/40 [==============================] - 0s 124us/sample - loss: 1.0140 - acc: 0.5000
Epoch 331/1000
40/40 [==============================] - 0s 125us/sample - loss: 1.0138 - acc: 0.5000
Epoch 332/1000
40/40 [==============================] - 0s 175us/sample - loss: 1.0135 - acc: 0.5000
Epoch 333/1000
40/40 [==============================] - 0s 100us/sample - loss: 1.0132 - acc: 0.5000
Epoch

40/40 [==============================] - 0s 100us/sample - loss: 0.9965 - acc: 0.5250
Epoch 485/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9965 - acc: 0.5250
Epoch 486/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9964 - acc: 0.5250
Epoch 487/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9968 - acc: 0.5250
Epoch 488/1000
40/40 [==============================] - 0s 100us/sample - loss: 0.9964 - acc: 0.5250
Epoch 489/1000
40/40 [==============================] - 0s 224us/sample - loss: 0.9964 - acc: 0.5000
Epoch 490/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9964 - acc: 0.5000
Epoch 491/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9964 - acc: 0.5000
Epoch 492/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9963 - acc: 0.5000
Epoch 493/1000
40/40 [==============================] - 0s 200us/sample - loss: 0.9963 - acc: 0.5000
Epoch

40/40 [==============================] - 0s 100us/sample - loss: 0.9889 - acc: 0.4750
Epoch 645/1000
40/40 [==============================] - 0s 199us/sample - loss: 0.9888 - acc: 0.4750
Epoch 646/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9887 - acc: 0.5000
Epoch 647/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9887 - acc: 0.5000
Epoch 648/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9887 - acc: 0.5000
Epoch 649/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9884 - acc: 0.5250
Epoch 650/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9884 - acc: 0.5250
Epoch 651/1000
40/40 [==============================] - 0s 200us/sample - loss: 0.9887 - acc: 0.5250
Epoch 652/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9884 - acc: 0.5250
Epoch 653/1000
40/40 [==============================] - 0s 149us/sample - loss: 0.9883 - acc: 0.5250
Epoch

40/40 [==============================] - 0s 150us/sample - loss: 0.9828 - acc: 0.5000
Epoch 806/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9828 - acc: 0.5000
Epoch 807/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9826 - acc: 0.5000
Epoch 808/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9825 - acc: 0.5000
Epoch 809/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9825 - acc: 0.5000
Epoch 810/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9825 - acc: 0.5000
Epoch 811/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9828 - acc: 0.5000
Epoch 812/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9828 - acc: 0.5000
Epoch 813/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9825 - acc: 0.5000
Epoch 814/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9825 - acc: 0.5000
Epoch

40/40 [==============================] - 0s 150us/sample - loss: 0.9761 - acc: 0.4750
Epoch 966/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9761 - acc: 0.4750
Epoch 967/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9760 - acc: 0.4750
Epoch 968/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9761 - acc: 0.4750
Epoch 969/1000
40/40 [==============================] - 0s 249us/sample - loss: 0.9760 - acc: 0.4750
Epoch 970/1000
40/40 [==============================] - 0s 125us/sample - loss: 0.9759 - acc: 0.4750
Epoch 971/1000
40/40 [==============================] - 0s 199us/sample - loss: 0.9759 - acc: 0.4750
Epoch 972/1000
40/40 [==============================] - 0s 150us/sample - loss: 0.9759 - acc: 0.4750
Epoch 973/1000
40/40 [==============================] - 0s 100us/sample - loss: 0.9759 - acc: 0.4750
Epoch 974/1000
40/40 [==============================] - 0s 175us/sample - loss: 0.9757 - acc: 0.4750
Epoch

In [26]:
ypred=b.predict(x_test)
ypred

array([[0.2635259 , 0.33108264, 0.40539145],
       [0.3835512 , 0.21587104, 0.4005778 ],
       [0.1988885 , 0.17688291, 0.62422866],
       [0.39810243, 0.03969352, 0.562204  ],
       [0.42174497, 0.18444443, 0.39381057],
       [0.3984433 , 0.23449743, 0.36705923],
       [0.2258141 , 0.56965804, 0.20452793],
       [0.2258141 , 0.56965804, 0.20452793],
       [0.22963654, 0.5530918 , 0.21727169],
       [0.22281514, 0.54063493, 0.23654999]], dtype=float32)

In [27]:
y_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [28]:
ypred[5]

array([0.3984433 , 0.23449743, 0.36705923], dtype=float32)

In [29]:
y_test[5]

array([1., 0., 0.], dtype=float32)

In [30]:
b.predict_classes(sc.transform([[144372.41,118671.85,383199.62,182901.99]]))

array([2], dtype=int64)