In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\smartbridge_datasets\Salary_Data.csv")

In [3]:
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
data.isnull().any()

YearsExperience    False
Salary             False
dtype: bool

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
YearsExperience    30 non-null float64
Salary             30 non-null float64
dtypes: float64(2)
memory usage: 560.0 bytes


In [6]:
x = data.iloc[:,0:1].values
y = data.iloc[:,1].values

In [7]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [8]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
e = Sequential()

In [13]:
e.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [14]:
e.add(Dense(2,kernel_initializer="random_uniform",activation="relu"))

In [15]:
e.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [17]:
e.compile("adam","mean_squared_error",metrics = ["MSE"])

In [19]:
e.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
24/24 [==============================] - 0s 166us/sample - loss: 6073890304.0000 - mean_squared_error: 6073890304.0000
Epoch 2/10
24/24 [==============================] - 0s 125us/sample - loss: 6073890304.0000 - mean_squared_error: 6073890304.0000
Epoch 3/10
24/24 [==============================] - 0s 83us/sample - loss: 6073890304.0000 - mean_squared_error: 6073890304.0000
Epoch 4/10
24/24 [==============================] - 0s 125us/sample - loss: 6073888768.0000 - mean_squared_error: 6073888768.0000
Epoch 5/10
24/24 [==============================] - 0s 167us/sample - loss: 6073889280.0000 - mean_squared_error: 6073889280.0000
Epoch 6/10
24/24 [==============================] - 0s 83us/sample - loss: 6073888768.0000 - mean_squared_error: 6073888768.0000
Epoch 7/10
24/24 [==============================] - 0s 83us/sample - loss: 6073888256.0000 - mean_squared_error: 6073888256.0000
Epoch 8/10
24/24 [==============================] - 0s 83us/sample - loss: 6073888256.0000 - 

In [20]:
ypred=e.predict(x_test)

In [21]:
ypred

array([[0.1381602 ],
       [0.15403293],
       [0.1393652 ],
       [0.13889204],
       [0.15214032],
       [0.15024771]], dtype=float32)

In [22]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431.])

In [23]:
ypred[2]

array([0.1393652], dtype=float32)

In [24]:
y_test[2]

57081.0

In [25]:
e.predict(sc.transform([[1.5]]))

array([[0.1381602]], dtype=float32)

In [26]:
e.predict_classes(sc.transform([[1.5]]))

array([[0]])