In [1]:
import numpy as np   
import pandas as pd       

In [2]:
df=pd.read_csv(r"C:\bank.csv")

In [3]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
df.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
df=df.drop(["marital","education","default"],axis=1)

In [6]:
df.head()

age         job  balance housing loan  contact  day month  duration  \
0   59      admin.     2343     yes   no  unknown    5   may      1042   
1   56      admin.       45      no   no  unknown    5   may      1467   
2   41  technician     1270     yes   no  unknown    5   may      1389   
3   55    services     2476     yes   no  unknown    5   may       579   
4   54      admin.      184      no   no  unknown    5   may       673   

   campaign  pdays  previous poutcome deposit  
0         1     -1         0  unknown     yes  
1         1     -1         0  unknown     yes  
2         1     -1         0  unknown     yes  
3         1     -1         0  unknown     yes  
4         2     -1         0  unknown     yes

In [7]:
df.job.unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [8]:
df.housing.unique()

array(['yes', 'no'], dtype=object)

In [9]:
df.loan.unique()

array(['no', 'yes'], dtype=object)

In [10]:
df.contact.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [11]:
df.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [12]:
df.poutcome.unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()      
df["job"]= le.fit_transform(df["job"])
df["housing"]= le.fit_transform(df["housing"])
df["loan"]= le.fit_transform(df["loan"])
df["contact"]= le.fit_transform(df["contact"])
df["month"]= le.fit_transform(df["month"])
df["poutcome"]= le.fit_transform(df["poutcome"])
df["deposit"]= le.fit_transform(df["deposit"])

In [14]:
x=df.iloc[:,:13].values
y=df.iloc[:,13].values

In [15]:
x

array([[  59,    0, 2343, ...,   -1,    0,    3],
       [  56,    0,   45, ...,   -1,    0,    3],
       [  41,    9, 1270, ...,   -1,    0,    3],
       ...,
       [  32,    9,   29, ...,   -1,    0,    3],
       [  43,    9,    0, ...,  172,    5,    0],
       [  34,    9,    0, ...,   -1,    0,    3]], dtype=int64)

In [16]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [17]:
x.shape

(11162, 13)

In [18]:
y.shape

(11162,)

In [19]:
df.head(10)

age  job  balance  housing  loan  contact  day  month  duration  campaign  \
0   59    0     2343        1     0        2    5      8      1042         1   
1   56    0       45        0     0        2    5      8      1467         1   
2   41    9     1270        1     0        2    5      8      1389         1   
3   55    7     2476        1     0        2    5      8       579         1   
4   54    0      184        0     0        2    5      8       673         2   
5   42    4        0        1     1        2    5      8       562         2   
6   56    4      830        1     1        2    6      8      1201         1   
7   60    5      545        1     0        2    6      8      1030         1   
8   37    9        1        1     0        2    6      8       608         1   
9   28    7     5090        1     0        2    6      8      1297         3   

   pdays  previous  poutcome  deposit  
0     -1         0         3        1  
1     -1         0         3        1  
2     -1         0         3        1  
3     -1         0         3        1  
4     -1         0         3        1  
5     -1         0         3        1  
6     -1         0         3        1  
7     -1         0         3        1  
8     -1         0         3        1  
9     -1         0         3        1

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=10)

In [21]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [22]:
x_test

array([[ 0.30355616, -0.11527207, -0.40717069, ..., -0.479803  ,
        -0.38004742,  0.52472111],
       [-0.77978927,  1.44285467, -0.33049416, ..., -0.479803  ,
        -0.38004742,  0.52472111],
       [ 2.38691275,  0.19635328, -0.38641111, ..., -0.479803  ,
        -0.38004742,  0.52472111],
       ...,
       [ 0.13688763,  0.81960397,  0.20356285, ...,  0.38154486,
         1.4294321 , -0.46572879],
       [-0.11311516, -1.05014811, -0.29198849, ..., -0.479803  ,
        -0.38004742,  0.52472111],
       [-1.11312632,  0.50797862, -0.24511201, ..., -0.479803  ,
        -0.38004742,  0.52472111]])

In [23]:
x_train

array([[ 0.90821897, -0.16027463, -0.28956114, ..., -0.48159565,
        -0.35931621,  0.51969995],
       [-0.94195648, -0.16027463, -0.581739  , ..., -0.48159565,
        -0.35931621,  0.51969995],
       [-0.60556094, -0.16027463,  0.34110433, ..., -0.48159565,
        -0.35931621,  0.51969995],
       ...,
       [ 0.2354279 , -0.16027463, -0.14271053, ..., -0.48159565,
        -0.35931621,  0.51969995],
       [-0.10096764,  1.3885264 , -0.43945844, ..., -0.48159565,
        -0.35931621,  0.51969995],
       [-0.85785759, -0.16027463, -0.18353622, ..., -0.48159565,
        -0.35931621,  0.51969995]])

In [24]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)

C:\Users\akhil\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
ypred=logreg.predict(x_test)
ypred

array([1, 1, 0, ..., 1, 1, 1])

In [26]:
y_test

array([0, 1, 0, ..., 1, 1, 1])

In [27]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(ypred,y_test)
accuracy

0.799373040752351

In [28]:
logreg.predict(sc.transform([[56,0,45,0,0,2,5,8,1467,1,-1,0,3]]))

array([1])