In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv(r"C:\smartbridge_datasets\petrol_consumption.csv")

In [3]:
dataset.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [4]:
dataset.isnull().any()

Petrol_tax                      False
Average_income                  False
Paved_Highways                  False
Population_Driver_licence(%)    False
Petrol_Consumption              False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
Petrol_tax                      48 non-null float64
Average_income                  48 non-null int64
Paved_Highways                  48 non-null int64
Population_Driver_licence(%)    48 non-null float64
Petrol_Consumption              48 non-null int64
dtypes: float64(2), int64(3)
memory usage: 2.0 KB


In [6]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [7]:
x

array([[9.0000e+00, 3.5710e+03, 1.9760e+03, 5.2500e-01],
       [9.0000e+00, 4.0920e+03, 1.2500e+03, 5.7200e-01],
       [9.0000e+00, 3.8650e+03, 1.5860e+03, 5.8000e-01],
       [7.5000e+00, 4.8700e+03, 2.3510e+03, 5.2900e-01],
       [8.0000e+00, 4.3990e+03, 4.3100e+02, 5.4400e-01],
       [1.0000e+01, 5.3420e+03, 1.3330e+03, 5.7100e-01],
       [8.0000e+00, 5.3190e+03, 1.1868e+04, 4.5100e-01],
       [8.0000e+00, 5.1260e+03, 2.1380e+03, 5.5300e-01],
       [8.0000e+00, 4.4470e+03, 8.5770e+03, 5.2900e-01],
       [7.0000e+00, 4.5120e+03, 8.5070e+03, 5.5200e-01],
       [8.0000e+00, 4.3910e+03, 5.9390e+03, 5.3000e-01],
       [7.5000e+00, 5.1260e+03, 1.4186e+04, 5.2500e-01],
       [7.0000e+00, 4.8170e+03, 6.9300e+03, 5.7400e-01],
       [7.0000e+00, 4.2070e+03, 6.5800e+03, 5.4500e-01],
       [7.0000e+00, 4.3320e+03, 8.1590e+03, 6.0800e-01],
       [7.0000e+00, 4.3180e+03, 1.0340e+04, 5.8600e-01],
       [7.0000e+00, 4.2060e+03, 8.5080e+03, 5.7200e-01],
       [7.0000e+00, 3.7180e+03,

In [8]:
y

array([541, 524, 561, 414, 410, 457, 344, 467, 464, 498, 580, 471, 525,
       508, 566, 635, 603, 714, 865, 640, 649, 540, 464, 547, 460, 566,
       577, 631, 574, 534, 571, 554, 577, 628, 487, 644, 640, 704, 648,
       968, 587, 699, 632, 591, 782, 510, 610, 524], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1000)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
d = Sequential()

In [13]:
d.add(Dense(4,kernel_initializer = "random_uniform",activation = "relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [14]:
d.add(Dense(8,kernel_initializer = "random_uniform",activation = "relu"))

In [15]:
d.add(Dense(1,kernel_initializer = "random_uniform",activation = "relu"))

In [16]:
d.compile("adam",loss="mean_squared_error",metrics = ["MSE"])

In [17]:
d.fit(x_train,y_train,batch_size = 32,epochs = 10)

Epoch 1/10
38/38 [==============================] - 0s 9ms/sample - loss: 362232.5641 - mean_squared_error: 362232.5625
Epoch 2/10
38/38 [==============================] - 0s 341us/sample - loss: 362230.2303 - mean_squared_error: 362230.2500
Epoch 3/10
38/38 [==============================] - 0s 577us/sample - loss: 362227.7582 - mean_squared_error: 362227.7500
Epoch 4/10
38/38 [==============================] - 0s 341us/sample - loss: 362225.2220 - mean_squared_error: 362225.2188
Epoch 5/10
38/38 [==============================] - 0s 236us/sample - loss: 362222.6398 - mean_squared_error: 362222.6250
Epoch 6/10
38/38 [==============================] - 0s 289us/sample - loss: 362220.0641 - mean_squared_error: 362220.0625
Epoch 7/10
38/38 [==============================] - 0s 341us/sample - loss: 362217.3701 - mean_squared_error: 362217.3750
Epoch 8/10
38/38 [==============================] - 0s 262us/sample - loss: 362214.6694 - mean_squared_error: 362214.6875
Epoch 9/10
38/38 [========

In [18]:
ypred=d.predict(x_test)
ypred

array([[0.02193487],
       [0.02193034],
       [0.02205753],
       [0.02219494],
       [0.02206455],
       [0.02221812],
       [0.02211217],
       [0.02201144],
       [0.0224469 ],
       [0.02195937]], dtype=float32)

In [19]:
y_test

array([498, 524, 464, 628, 554, 344, 414, 587, 561, 635], dtype=int64)

In [20]:
ypred[4]

array([0.02206455], dtype=float32)

In [21]:
y_test[4]

554

In [22]:
d.predict(sc.transform([[8.0,4399,431,0.544]]))

array([[0.02221125]], dtype=float32)

In [23]:
d.predict_classes(sc.transform([[8.0,4399,431,0.544]]))

array([[0]])