In [1]:
import numpy as np   
import pandas as pd  

In [2]:
df=pd.read_csv(r"C:\Fish.csv")

In [3]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
df.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
df.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
df.shape

(159, 7)

In [7]:
x=df.iloc[:,[0,2,3,4,5,6]].values
y=df.iloc[:,1].values

In [8]:
x.shape

(159, 6)

In [9]:
y.shape

(159,)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

In [11]:
x.shape

(159, 12)

In [12]:
x

array([[1.0, 0.0, 0.0, ..., 30.0, 11.52, 4.02],
       [1.0, 0.0, 0.0, ..., 31.2, 12.48, 4.3056],
       [1.0, 0.0, 0.0, ..., 31.1, 12.3778, 4.6961],
       ...,
       [0.0, 0.0, 0.0, ..., 13.8, 2.2769999999999997, 1.2558],
       [0.0, 0.0, 0.0, ..., 15.2, 2.8728, 2.0672],
       [0.0, 0.0, 0.0, ..., 16.2, 2.9322, 1.8792]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=0)

In [14]:
from sklearn.linear_model import LinearRegression
mlr=LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
ypred=mlr.predict(x_test)
ypred

array([ 428.88533577,   98.08363614,  216.67998922,  208.66936638,
        657.24094116,  876.38855413,  665.97861965,  407.27203048,
        965.65306863,  146.62291102,  255.15532231,  561.63685124,
        765.67575361, 1012.38234027, -118.72798063,   14.47341216,
        137.60789564, 1155.53572308,  170.97092949,  724.93548455,
       -128.48675188,  525.45508599,  175.3519065 , 1322.74816983,
        -23.0873263 ,  475.44172778,  719.96841977,  280.94571114,
        885.12085107,  -16.63412226,  585.26038657,  164.22863371])

In [16]:
y_test

array([ 390. ,    0. ,  170. ,  160. ,  556. ,  900. ,  800. ,  300. ,
        975. ,  115. ,  200. ,  456. , 1000. , 1000. ,   60. ,   78. ,
        145. , 1600. ,  130. ,  720. ,   55. ,  390. ,  120. , 1650. ,
         90. ,  450. ,  700. ,  270. ,  850. ,    9.7,  650. ,  110. ])

In [17]:
from sklearn.metrics import r2_score
accuracy=r2_score(ypred,y_test)
accuracy

0.8813066271385556

In [18]:
mlr.predict([[1,0,0,0,0,0,0,26.3,29,33.5,12.73,4.4555]])

array([419.87180999])

In [19]:
mlr.predict(ct.transform([["Bream",26.3,29,33.5,12.73,4.4555]]))

array([419.87180999])