In [1]:
import numpy as np   
import pandas as pd                           

In [2]:
df=pd.read_csv(r"C:\smartbridge_datasets\diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            8      183             64              0        0  23.3   
2            0      137             40             35      168  43.1   
3            3       78             50             32       88  31.0   
4            2      197             70             45      543  30.5   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos  
1                     0.672   32      pos  
2                     2.288   33      pos  
3                     0.248   26      pos  
4                     0.158   53      pos

In [4]:
df.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Diabetes                    False
dtype: bool

In [5]:
df.Diabetes.unique()

array(['pos', 'neg'], dtype=object)

In [6]:
x=df.iloc[:,0:8].values
y=df.iloc[:,8:9].values

In [7]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
y

array([['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       ['pos'],
       [

In [9]:
y.shape

(549, 1)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [11]:
y.shape

(549, 2)

In [12]:
y

array([[0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       ...,
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=0)

In [14]:
x_train=np.asarray(x_train).astype('float32')
x_test=np.asarray(x_test).astype('float32')
y_train=np.asarray(y_train).astype('float32')
y_test=np.asarray(y_test).astype('float32')

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential   
from tensorflow.keras.layers import Dense

In [18]:
a=Sequential()

In [19]:
a.add(Dense(8,kernel_initializer= "random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [20]:
a.add(Dense(16,kernel_initializer= "random_uniform",activation="relu"))

In [21]:
a.add(Dense(2,kernel_initializer= "random_uniform",activation="softmax"))

In [22]:
a.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [23]:
a.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
439/439 [==============================] - 0s 434us/sample - loss: 0.6932 - acc: 0.4920
Epoch 2/1000
439/439 [==============================] - 0s 58us/sample - loss: 0.6926 - acc: 0.5011
Epoch 3/1000
439/439 [==============================] - 0s 49us/sample - loss: 0.6908 - acc: 0.7062
Epoch 4/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.6848 - acc: 0.7699
Epoch 5/1000
439/439 [==============================] - 0s 65us/sample - loss: 0.6722 - acc: 0.7563
Epoch 6/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.6498 - acc: 0.7540
Epoch 7/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.6190 - acc: 0.7540
Epoch 8/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.5823 - acc: 0.7585
Epoch 9/1000
439/439 [==============================] - 0s 59us/sample - loss: 0.5479 - acc: 0.7608
Epoch 10/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.5177 - acc: 0.760

439/439 [==============================] - 0s 50us/sample - loss: 0.3949 - acc: 0.8292
Epoch 163/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3946 - acc: 0.8292
Epoch 164/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3944 - acc: 0.8292
Epoch 165/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3944 - acc: 0.8337
Epoch 166/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3936 - acc: 0.8292
Epoch 167/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3938 - acc: 0.8292
Epoch 168/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3937 - acc: 0.8292
Epoch 169/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3935 - acc: 0.8246
Epoch 170/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3942 - acc: 0.8314
Epoch 171/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3930 - acc: 0.

439/439 [==============================] - 0s 52us/sample - loss: 0.3758 - acc: 0.8474
Epoch 323/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3769 - acc: 0.8360
Epoch 324/1000
439/439 [==============================] - 0s 64us/sample - loss: 0.3770 - acc: 0.8405
Epoch 325/1000
439/439 [==============================] - 0s 61us/sample - loss: 0.3763 - acc: 0.8405
Epoch 326/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3761 - acc: 0.8405
Epoch 327/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3762 - acc: 0.8405
Epoch 328/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3756 - acc: 0.8405
Epoch 329/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3757 - acc: 0.8405
Epoch 330/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3757 - acc: 0.8428
Epoch 331/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3759 - acc: 0.

439/439 [==============================] - 0s 55us/sample - loss: 0.3736 - acc: 0.8428
Epoch 403/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3729 - acc: 0.8360
Epoch 404/1000
439/439 [==============================] - 0s 57us/sample - loss: 0.3731 - acc: 0.8383
Epoch 405/1000
439/439 [==============================] - 0s 41us/sample - loss: 0.3726 - acc: 0.8337
Epoch 406/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3734 - acc: 0.8337
Epoch 407/1000
439/439 [==============================] - 0s 41us/sample - loss: 0.3727 - acc: 0.8360
Epoch 408/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3724 - acc: 0.8519
Epoch 409/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3722 - acc: 0.8383
Epoch 410/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3762 - acc: 0.8428
Epoch 411/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3722 - acc: 0.

439/439 [==============================] - 0s 45us/sample - loss: 0.3550 - acc: 0.8610
Epoch 563/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3549 - acc: 0.8633
Epoch 564/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3575 - acc: 0.8633
Epoch 565/1000
439/439 [==============================] - 0s 41us/sample - loss: 0.3566 - acc: 0.8679
Epoch 566/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3541 - acc: 0.8633
Epoch 567/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3562 - acc: 0.8656
Epoch 568/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3532 - acc: 0.8656
Epoch 569/1000
439/439 [==============================] - 0s 41us/sample - loss: 0.3531 - acc: 0.8656
Epoch 570/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3551 - acc: 0.8633
Epoch 571/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3569 - acc: 0.

439/439 [==============================] - 0s 50us/sample - loss: 0.3436 - acc: 0.8702
Epoch 643/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3444 - acc: 0.8702
Epoch 644/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3437 - acc: 0.8724
Epoch 645/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3434 - acc: 0.8747
Epoch 646/1000
439/439 [==============================] - 0s 41us/sample - loss: 0.3440 - acc: 0.8724
Epoch 647/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3444 - acc: 0.8702
Epoch 648/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3443 - acc: 0.8770
Epoch 649/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3448 - acc: 0.8656
Epoch 650/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3434 - acc: 0.8724
Epoch 651/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3428 - acc: 0.

439/439 [==============================] - 0s 45us/sample - loss: 0.3342 - acc: 0.8724
Epoch 803/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3300 - acc: 0.8702
Epoch 804/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3319 - acc: 0.8724
Epoch 805/1000
439/439 [==============================] - 0s 45us/sample - loss: 0.3304 - acc: 0.8724
Epoch 806/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3318 - acc: 0.8724
Epoch 807/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3312 - acc: 0.8747
Epoch 808/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3308 - acc: 0.8747
Epoch 809/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3308 - acc: 0.8702
Epoch 810/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3311 - acc: 0.8747
Epoch 811/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3307 - acc: 0.

439/439 [==============================] - 0s 52us/sample - loss: 0.3293 - acc: 0.8770
Epoch 963/1000
439/439 [==============================] - 0s 55us/sample - loss: 0.3269 - acc: 0.8770
Epoch 964/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3301 - acc: 0.8793
Epoch 965/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3285 - acc: 0.8793
Epoch 966/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3277 - acc: 0.8793
Epoch 967/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3274 - acc: 0.8793
Epoch 968/1000
439/439 [==============================] - 0s 43us/sample - loss: 0.3295 - acc: 0.8793
Epoch 969/1000
439/439 [==============================] - 0s 50us/sample - loss: 0.3288 - acc: 0.8770
Epoch 970/1000
439/439 [==============================] - 0s 52us/sample - loss: 0.3275 - acc: 0.8838
Epoch 971/1000
439/439 [==============================] - 0s 48us/sample - loss: 0.3265 - acc: 0.

In [24]:
ypred=a.predict(x_test)
ypred

array([[1.25407144e-01, 8.74592841e-01],
       [6.10550791e-02, 9.38944936e-01],
       [9.54440594e-01, 4.55594361e-02],
       [8.49187747e-03, 9.91508126e-01],
       [9.85216022e-01, 1.47840045e-02],
       [1.20292222e-02, 9.87970769e-01],
       [9.60171700e-01, 3.98283638e-02],
       [3.48470509e-02, 9.65152979e-01],
       [5.77195108e-01, 4.22804892e-01],
       [5.01030241e-04, 9.99498963e-01],
       [9.85181987e-01, 1.48179913e-02],
       [2.42657602e-01, 7.57342339e-01],
       [1.06344298e-01, 8.93655777e-01],
       [8.97122443e-01, 1.02877565e-01],
       [7.90213525e-01, 2.09786445e-01],
       [4.72850390e-02, 9.52714980e-01],
       [9.66037512e-01, 3.39625143e-02],
       [7.12666631e-01, 2.87333399e-01],
       [5.13156831e-01, 4.86843169e-01],
       [4.31355357e-01, 5.68644643e-01],
       [9.91418123e-01, 8.58190283e-03],
       [4.09204692e-01, 5.90795279e-01],
       [4.07998621e-01, 5.92001438e-01],
       [1.54379115e-03, 9.98456240e-01],
       [9.987556

In [25]:
y_test

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [26]:
ypred[1]

array([0.06105508, 0.93894494], dtype=float32)

In [27]:
y_test[1]

array([1., 0.], dtype=float32)

In [28]:
a.predict(sc.transform([[8,183,64,0,0,23.3,0.672,32]]))

array([[0.96759695, 0.03240306]], dtype=float32)

In [29]:
a.predict_classes(sc.transform([[8,183,64,0,0,23.3,0.672,32]]))

array([0], dtype=int64)